### ISSUE TITLE
Разработка Dashboard

### ISSUE THREAD

**Issue by pc-mist** [netsuileo/sfu-cluster-dashboard#1]
1. Верстка - продолжать верстать;
2. Шаблонизатор Jinja - подключить, разбить всё по шаблонам;
3. Knockout.js;
4. Chart.js - Сделать графики.

**Comment by netsuileo** [comment]
https://github.com/MongoEngine/django-mongoengine
Поюзай вместо простого mongoengine. Если есть готовая интеграция -- зачем городить свою.

**Comment by pc-mist** [comment]
Пытался. Не осилил. Да и архитектуру базы будем переделывать. Слишком сложно получилось.
